### ISSUE TITLE
Issue with the cp command

### ISSUE THREAD

**Issue by gfirem** [CodeAtCode/freemius-suite#8]
The attribute -a include -r. I get and error in Mac when run your script. Also thanks for your nice scripts.

More in the next link. 
https://www.computerhope.com/unix/ucp.htm

https://github.com/CodeAtCode/freemius-suite/blob/345848b247368167d9344a753eb04696c15ecf56/package.sh#L27

**Comment by Mte90** [comment]
Good to know probably the glibc/unix suite has different commands on mac :-)
